services:
  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    env_file:
      - .env
    depends_on:
      - pg-db
    restart: always
    networks:
      - my_network

  pg-db:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    restart: always
    networks:
      - my_network

networks:
  my_network: