services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432